baseURL = 'https://www.clonk.au/'
languageCode = 'en-au'
title = 'Clonk'
theme = "researcher"

[params.style]  # appearance options (can be modified but not removed)
   fontFamily = "Arial"
   pageWidth = "750px"
   avatarSize = "90px"
   colorBlack = "#222222"
   colorRed = "#dc3545"
